"Colors
colorscheme gruvbox
syntax enable 
"Spaces & Tabs"
set backspace=indent,eol,start
set tabstop=4
set shiftwidth=4
"set expandtab"
set mouse+=a
set list
set listchars=tab:›\ ,trail:•,extends:#,nbsp:.
let mapleader=','
"UI Config
set number
set cursorline
set wildmenu
set wildmode=longest:full,full
set lazyredraw
set showmatch
"Plug
call plug#begin()
    Plug 'kelwin/vim-smali'
    Plug 'scrooloose/nerdcommenter'
call plug#end()
