#!/bin/env zsh

export ANDROID_HOME="/Users/$USER/Library/Android/sdk"
export SCRIPTS="$HOME/Scripts"

export PATH="${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
export PATH="${PATH}:$SCRIPTS"

export ZSH=$HOME/.oh-my-zsh
export DEFAULT_USER=$USER
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


#--------------------#
#      ALIASES       #
#--------------------#
eval $(thefuck --alias)
alias upgrade="brew update && brew upgrade"
alias server="python -m SimpleHTTPServer"
alias fiind="find . -name"
alias rm="trash"
alias c="clear"

#--------------------#
#    ENVIRONMENT     #
#--------------------#
ZSH_THEME="mh_edit"
plugins=(git z colored-man-pages common-aliases safe-rm)
source $ZSH/oh-my-zsh.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#--------------------#
#     UTILITIES      #
#--------------------#
function mk(){
    mkdir -p "$@" && cd "$@"
}

function man2pdf() {
     man -t "${1}" | /usr/bin/open -f -a /Applications/Preview.app/
}

#--------------------#
#     ANDROID RE     #
#--------------------#
function package(){
	adb shell su -c pm list packages | grep $1 | cut -d ":" -f 2
}

function pgkill() {
    adb shell "for pid in  \`ps  | $1 | sed 's/  */ /g' | \
     cut -d ' '  -f 2 \`; do kill \$pid; done"
}

function frida-start() {
    pgkill "frida" 
    if [ -n "$1" ]; then frida=$1; else frida="frida-server"; fi
    adb shell "su -c /data/local/tmp/$frida &"
}

function gdb-start() {
    pgkill "gdbserver"
    if [ -n "$2" ]; then gdb=$2; else gdb="gdbserver"; fi
	pid=$(adb shell su -c pgrep $1)
	adb shell "su -c /data/local/tmp/$gdb :9999 --attach $pid &"
}
